name: Build and Release

on:
  push:
    tags:
      - "v*"
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.project }} for ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: linux-x64
            output: linux64
            project: server
          - os: ubuntu-latest
            arch: linux-arm64
            output: linux-arm64
            project: server
          - os: windows-latest
            arch: win-x64
            output: win64
            project: server
          - os: windows-latest
            arch: win-x64
            output: win64
            project: client
      fail-fast: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Install NuGet
        if: runner.os == 'Windows'
        run: |
          nuget update -self
          nuget install nuget.commandline -OutputDirectory .nuget -ExcludeVersion
          echo "$(pwd)/.nuget/nuget.commandline/tools" >> $GITHUB_PATH

      - name: Restore .NET workloads
        run: |
          dotnet workload restore

      - name: Add msbuild to PATH
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v2
        
      - name: Restore NuGet dependencies for GPSS
        if: runner.os == 'Windows'
        run: nuget restore ${{ github.workspace }}/GPSS.sln -NoCache

      - name: Publish ${{ matrix.project }} ${{ matrix.arch }}
        shell: bash
        run: |
          PROJECT_PATH=""
          if [ "${{ matrix.project }}" = "server" ]; then
            PROJECT_PATH="Server/GPSS Server.csproj"
            EXECUTABLE_NAME="GPSS Server"
          else
            PROJECT_PATH="Client/GPSS Client.csproj"
            EXECUTABLE_NAME="GPSS Client"
          fi
          FRAMEWORK=""
          if [ "${{ matrix.project }}" = "client" ]; then
            FRAMEWORK="-f net9.0-windows10.0.19041.0"
          fi
          dotnet publish "$PROJECT_PATH" -c Release -o ./output/${{ matrix.output }}-${{ matrix.project }} --self-contained true \
            -p:PublishReadyToRun=true -p:PublishSingleFile=true \
            -p:EnableCompressionInSingleFile=true \
            -p:DebugType=None -p:DebugSymbols=false \
            -r ${{ matrix.arch }} $FRAMEWORK

      - name: Set execute permissions (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          EXECUTABLE="GPSS Server"
          if [ "${{ matrix.project }}" = "client" ]; then
            EXECUTABLE="GPSS Client"
          fi
          chmod +x "./output/${{ matrix.output }}-${{ matrix.project }}/${EXECUTABLE}"

      - name: Create ZIP archive
        shell: bash
        run: |
          cd output
          ZIPNAME="../${{ matrix.output }}-${{ matrix.project }}.zip"
          DIRNAME="${{ matrix.output }}-${{ matrix.project }}"
          if [ "${{ runner.os }}" = "Windows" ]; then
            7z a -tzip "$ZIPNAME" "$DIRNAME"/*
          else
            zip -r "$ZIPNAME" "$DIRNAME"/*
          fi

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}-${{ matrix.project }}
          path: ${{ matrix.output }}-${{ matrix.project }}.zip
          retention-days: 1

  check-tag:
    name: Check if tag is on master
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    outputs:
      is_master: ${{ steps.check.outputs.is_master }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to fetch all tags and history

      - name: Check if tag is on master
        id: check
        run: |
          TAG_SHA=$(git rev-parse ${{ github.ref_name }})
          MASTER_SHA=$(git rev-parse origin/master)
          if [ "$TAG_SHA" = "$MASTER_SHA" ]; then
            echo "is_master=true" >> $GITHUB_OUTPUT
          else
            echo "is_master=false" >> $GITHUB_OUTPUT
          fi

  release:
    name: Create Release
    needs: [build, check-tag]
    runs-on: ubuntu-latest
    if: needs.check-tag.outputs.is_master == 'true'

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          body: "Fill me in before releasing this."
          draft: true
          prerelease: false