name: Build and Release

on:
  push:
    tags:
      - "v*"
    branches:
      - "master"
    paths:
      - "**.cs"
      - "**.dll"
      - "**.csproj"
      - "**.sln"
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.project }} for ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: linux-x64
            output: linux64
          - os: ubuntu-latest
            arch: linux-arm64
            output: linux-arm64
          - os: macos-latest
            arch: osx-x64
            output: osx64
          - os: windows-latest
            arch: win-x64
            output: win64
        project: [server, client]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      # Temporary step to ensure all workloads are available
      - name: Restore .NET workloads
        run: dotnet workload restore

      - name: Restore NuGet dependencies for GPSS
        run: nuget restore ${{ github.workspace }}/GPSS.sln -NoCache

      - name: Publish ${{ matrix.project }} ${{ matrix.arch }}
        shell: bash
        run: |
          PROJECT_PATH=""
          if [ "${{ matrix.project }}" = "server" ]; then
            PROJECT_PATH="Server/GPSS Server.csproj"
            EXECUTABLE_NAME="GPSS Server"
          else
            PROJECT_PATH="Client/GPSS Client.csproj"
            EXECUTABLE_NAME="GPSS Client"
          fi
          dotnet publish "$PROJECT_PATH" -c Release -o ./output/${{ matrix.output }}-${{ matrix.project }} --self-contained true \
            -p:PublishReadyToRun=true -p:PublishSingleFile=true \
            -p:EnableCompressionInSingleFile=true \
            -r ${{ matrix.arch }}

      - name: Set execute permissions (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          EXECUTABLE="GPSS Server"
          if [ "${{ matrix.project }}" = "client" ]; then
            EXECUTABLE="GPSS Client"
          fi
          chmod +x "./output/${{ matrix.output }}-${{ matrix.project }}/${EXECUTABLE}"

      - name: Create ZIP archive
        shell: bash
        run: |
          cd output
          ZIPNAME="../${{ matrix.output }}-${{ matrix.project }}.zip"
          DIRNAME="${{ matrix.output }}-${{ matrix.project }}"
          if [ "${{ runner.os }}" = "Windows" ]; then
            7z a -tzip "$ZIPNAME" "$DIRNAME"/*
          else
            zip -r "$ZIPNAME" "$DIRNAME"/*
          fi

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}-${{ matrix.project }}
          path: ${{ matrix.output }}-${{ matrix.project }}.zip
          retention-days: 1

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          body: "Fill me in before releasing this."
          draft: true
          prerelease: false